### ISSUE TITLE
[ADC] Implement built-in ADC

### ISSUE THREAD

**Issue by rgw3d** [IlliniHyperloopComputing/Pod#108]
The goal is to read values from the 7 built-in ADCs on the BBB. One way to do this is by individually reading each sensor. However, I discovered another way of doing this using a buffer that is built into the kernel. 

Essentially, the kernel handles reading all of the ADCs at once, and posting their values in a file. Then you can read this file, parse the bytes and get all of the ADC values at once. 

Follow the guide in Pod/BBBSetup/adc_testing to see the progress that has been made -- the kernel handles all of the heavy lifting, what is needed is to continue to simplify and understand `simplified_buffer.c` and determine what can be run as a setup script, and what needs to actually make its way into the main code base (ADC manager). 

for more information about the `/sys` filesystem from where the ADC is accessible: https://en.wikipedia.org/wiki/Sysfs

**Comment by schmidtwmark** [comment]
This functionality should be added to ADCManager's refresh and initialize functions. The scaffolding is all there and ready to go.
