### ISSUE TITLE
Internal warnings and errors

### ISSUE THREAD

**Issue by rgw3d** [IlliniHyperloopComputing/Pod#113]
In order to be safe, the pod software must be able to check the sensor data it is receiving to determine if any errors are happening.

We can have a variety of errors, most of them shutting down the pod. Shutting down the pod might entail shutting off just the HV battery, or if we are in flight also enabling the brakes. 

Communication failure 
Sensor failure/ not communicating 
Temperature High (on battery)
Under/Over voltage (on battery)

**Where do we check for this?**
Probably in each source manager (and in the network manager as well for the TCP communication) we ought to develop some sort of configurable function that checks a piece of data to make sure that we don't have some sort of anomaly.

**Comment by schmidtwmark** [comment]
In the `refresh()` function in each SourceManager, we can check that certain values are within acceptable ranges. 

Then, these commands can be passed through to each individual state, where they can be handled appropriately.
