### ISSUE TITLE
Assertion in State Machine

### ISSUE THREAD

**Issue by epaglier** [IlliniHyperloopComputing/Pod#91]
I think that we should not use the assert command due to the fact that if it fails we error out and our state machine fails. We should instead use an if or try catch that will allow us to just transition to an error state.

**Comment by rgw3d** [comment]
I suggest keeping the `assert()` in the testing/ debug versions of the code. 

We already have Defines built into our build process for Simulation or Debug builds.

Something like:
`#if defined(SIM) || defined(DEBUG)`
is already supported in our build. That way the assertion doesn't make it into prod


However...
I we already include the define `NDEBUG` in our build of the prod version, which should already disable the assert()
https://stackoverflow.com/questions/5354314/how-to-completely-disable-assertion
So this isn't an issue
